// <auto-generated />
namespace Vidly_Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddMoviePropertiesAndGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMoviePropertiesAndGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "202109100919100_AddMoviePropertiesAndGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
